apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: productpage-v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productpage-v1
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 20

